timezone: 'America/New_York'
permalink: 'blog/:year/:title.html'
paginate: 10
pagination_path: 'blog/page:num'

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - bin
  - config.ru
  - images

# Plugin settings
markdown: redcarpet
highlighter: true
redcarpet:
  extensions: [smart, tables]

sass:
  sass_dir: stylesheets
  style: compressed

# Blog info
title: "code.nevercraft.net"
url: http://code.nevercraft.net
