timezone: 'America/New_York'
pygments: true
permalink: 'blog/:year/:title.html'
paginate: 10
pagination_path: 'blog/page:num'

exclude:
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - bin
  - config.ru
  - images
  - vendor

# Plugin settings
markdown: redcarpet
redcarpet:
  extensions: [smart, tables]

# Blog info
title: "code.nevercraft.net"
url: http://code.nevercraft.net
