auto:        true
server_port: 4000
pygments:    true
permalink:   /blog/:year/:title.html
paginate:    10

exclude: _script _lib _drafts config.ru CNAME README.markdown Rakefile Gemfile
         Gemfile.lock

# Plugin settings
markdown: redcarpet

title: code.nevercraft.net
url:   http://code.nevercraft.net

# Gravatar
gravatar_hash: 041cd7558aa5868a21d949c88e195c95
