# Site settings
title: code.nevercraft.net
email: code@nevercraft.net
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://code.nevercraft.net"
twitter_username: itspriddle
github_username:  itspriddle

# Plugin settings
markdown: redcarpet
redcarpet:
  extensions: [smart, tables]

timezone: 'America/New_York'

# Permalink settings
permalink: 'blog/:year/:title.html'
paginate: 10
pagination_path: 'blog/page:num'

# Files to exclude
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - bin
  - config.ru
  - images

# Sass setup
sass:
  sass_dir: stylesheets
  style: compressed
