auto:        false
server:      false
pygments:    true
permalink:   /blog/:year/:title.html
paginate:    10

exclude: bin config.ru Gemfile Gemfile.lock README.markdown

# Plugin settings
markdown: redcarpet

title: code.nevercraft.net
url:   http://code.nevercraft.net

# Gravatar
gravatar_hash: 041cd7558aa5868a21d949c88e195c95
