auto:        true
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   /posts/:year/:month/:day/:title
paginate:    5
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
site_name: 'itspriddle.github.com'
site_url: 'http://itspriddle.github.com/'
author: Josh
author_url: 'http://twitter.com/itspriddle'

