# Site settings
title: josh.fail
description: Random thoughts about programming.

analytics:
  google: UA-358917-9

author:
  name: Joshua Priddle
  email: jpriddle@me.com
  linkedin: itspriddle
  github: itspriddle
  twitter: itspriddle
  location: Halfmoon, NY, USA

# Plugin settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

timezone: 'America/New_York'

# Permalink settings
permalink: ':categories/:year/:title.html'

# Pagination settings Tried enabling this on 2022-01-24 and found it requires
# moving from post.html => post/index.html for permalinks. Not sure I want to
# just yet
# paginate: 10
# paginate_path: 'browse/page:num'

# Files to exclude
exclude:
  - .tags
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin

# Sass setup
sass:
  sass_dir: stylesheets
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Collections
# TODO - to generate pages for each project, need to make a new layout
collections:
  - projects_work
  - projects_open_source

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"
  # -
  #   scope:
  #     path: ""
  #     category: dev
  #   values:
  #     paginate_path: 'dev/browse/page:num'
