# Site settings
title: code.nevercraft.net
email: code@nevercraft.net
description: Random thoughts about programming.
url: "http://code.nevercraft.net"

# Social
twitter_username: itspriddle
github_username:  itspriddle

# Plugin settings
markdown: redcarpet
redcarpet:
  extensions: [smart, tables]

timezone: 'America/New_York'

# Permalink settings
permalink: 'blog/:year/:title.html'
# paginate: 10
# pagination_path: 'blog/page:num'

# Files to exclude
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - bin
  - config.ru
  - images

# Sass setup
sass:
  sass_dir: stylesheets
  style: compressed

# Gems
gems:
  - jekyll-feed
