# Site settings
url: https://josh.fail
title: josh.fail
description: Random thoughts about programming.

analytics:
  google: UA-358917-9

author:
  name: Joshua Priddle
  email: jpriddle@me.com
  linkedin: itspriddle
  github: itspriddle
  twitter: itspriddle
  location: Halfmoon, NY, USA

# Plugin settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

timezone: 'America/New_York'

# Permalink settings
permalink: '/:year/:title/'

# Pagination settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page:num/'
  title: ':title - page :num'
  sort_reverse: true

# Files to exclude
exclude:
  - .tags
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor

include:
  - _pages

# Sass setup
sass:
  sass_dir: stylesheets
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"
