auto:        true
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   /posts/:year/:month/:day/:title.html
paginate:    5
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
site_name: 'blog.nevercraft.net'
site_url: 'http://blog.nevercraft.net/'
author: Josh
author_url: 'http://twitter.com/itspriddle'
