auto:        true
server_port: 4000
pygments:    true
markdown:    rdiscount
permalink:   /blog/:year/:title.html
rdiscount:
  extensions: [smart]
paginate:    5
exclude: _script
site_name: code.nevercraft.net
