# Site settings
title: josh.fail
description: Random thoughts about programming.

analytics:
  google: UA-358917-9

author:
  name: Joshua Priddle
  email: jpriddle@me.com
  linkedin: itspriddle
  github: itspriddle
  twitter: itspriddle
  location: Halfmoon, NY, USA

# Plugin settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

timezone: 'America/New_York'

# Permalink settings
permalink: ':categories/:year/:title.html'
# paginate: 10
# pagination_path: 'blog/page:num'

# Files to exclude
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - bin

# Sass setup
sass:
  sass_dir: stylesheets
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Collections
# TODO - to generate pages for each project, need to make a new layout
collections:
  - projects_work
  - projects_open_source

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"
