source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-feed"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-paginate-v2"
gem "jekyll-redirect-from"
gem "jekyll-sitemap"
gem "jemoji"
