name: Lint GitHub Actions

on:
  pull_request:
    branches:
      - main

    paths:
      - '.github/workflows/*.yml'

permissions:
  contents: read

jobs:
  action-lint:
    name: Run actionlint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Configure actionlint
        run: |
          echo "::add-matcher::.github/matchers/actionlint.json"
        shell: bash

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false
